### ISSUE TITLE
Add label for PR to be counted for hacktoberfest

### ISSUE THREAD

**Issue by saileshbro** [ashiishme/open-source-enthusiasts#106]
Hey,
According to [this](https://hacktoberfest.digitalocean.com/hacktoberfest-update) link. For ones PR to be counted, it should be tagged as with `hacktoberfest` label.

**Comment by ashiishme** [comment]
This has already been addressed because I am using `Hacktoberfest` in the repository topic & for the PR, it must either have `hacktoberfest-accepted` label or it must be `approved` or `merged`. So, most of the PR's are merged which should be eligible unless the `Hacktoberfest Team` rejects due to only updating a `md` file.
